version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
    ports:
      - 5432:5432
  # backend-app:
  #   image: express-backend-api
  #   environment:
  #     HOST: db
  #   ports:
  #     - 3000:3000
